### ISSUE TITLE
恩，你说对了，是watch

### ISSUE THREAD

**Issue by 1160300704** [TheSecondDavid/I-looklook-watching#1]
但是为什么我俩那个项目没有issue呢，是因为没有不同么，还是fork，这是不是要学不要试，我个傻逼

**Comment by TheSecondDavid** [comment]
不知道，但是这个issue也不在主页显示就太恶心了？？？它怎么居然不在主页显示呢？那我怎么知道别人有问题提出？

**Comment by 1160300704** [comment]
额，不知道，但是现在你能看见了，因为你说了issue他就会变为第一active，唉，用不懂，应该学，要学

**Comment by TheSecondDavid** [comment]
不，我看不到你的提交，我只看到我的提交，是不是这是你开的issue，我主场我居然看不到，额，我试试我开
