### ISSUE TITLE
主场自开issue

### ISSUE THREAD

**Issue by TheSecondDavid** [TheSecondDavid/I-looklook-watching#2]
啊啊啊啊啊啊啊啊啊啊，现在最大的问题是邮件和主页。邮件提醒能不能换成主页！！！又超又讨厌，outlook不是不提醒么，不听好么，是不是后开的号自动设置改版了，啊啊啊啊，唉唉唉

**Comment by 1160300704** [comment]
然后你把close了老子也看不到了，呵呵。

**Comment by 1160300704** [comment]
还有，我发现我左边能够查看所有和我有关，pull，fork和issue过的仓库

**Comment by TheSecondDavid** [comment]
没错这边能看到

**Comment by TheSecondDavid** [comment]
而且更新和同步的好快啊

**Comment by 1160300704** [comment]
诶？我这块有邮件接收，还有你这个issue我不能close
真是神奇的架构和权限，靠，可气弄不懂

**Comment by TheSecondDavid** [comment]
行，那我先关了，你再开试试，顺便告诉我这回邮件接到了么
